// <auto-generated />
namespace UpdateMe.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Assignmenttocurrentquizstate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Assignmenttocurrentquizstate));
        
        string IMigrationMetadata.Id
        {
            get { return "201711151458172_Assignment to current quiz state"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
